workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build APK Release
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - ayoubboutglay318@gmail.com

  ios-release:
    name: iOS App Store Release
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS app for App Store
        script: flutter build ios --release
    artifacts:
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - ayoubboutglay318@gmail.com
